/**
 * BionicHub 产品数据库 — 仅高擎动力 (HighTorque) + 灵心巧手 (LinkerBot)
 *
 * 数据来源：
 *   - 高擎动力招标规格及报价表 (USD) — Ex-work Price
 *   - 灵心巧手产品手册 20260513 英文版 — Ex-work Price
 *   - 原 data.js 中灵心巧手的历史价格
 *
 * 分类体系：
 *   dexterous-hand    灵巧手
 *   humanoid-robot    人形机器人
 *   robot-arm         机械臂
 *   joint-module       关节模组
 *   accessory          配件
 *   teleoperation      遥操作设备
 */

// ========== Category Labels ==========
const CATEGORIES = {
  "dexterous-hand": "Dexterous Hand",
  "humanoid-robot": "Humanoid Robot",
  "robot-arm": "Robot Arm",
  "joint-module": "Joint Module",
  "accessory": "Accessory",
  "teleoperation": "Teleoperation Device",
};

// ========== Brands ==========
const BRANDS = {
  "HighTorque": "HighTorque Robotics",
  "LinkerBot": "LinkerBot",
};

// ========== Sort Options ==========
const SORT_OPTIONS = {
  "featured": "Featured",
  "price-asc": "Price: Low to High",
  "price-desc": "Price: High to Low",
  "name": "Name: A-Z",
};

// ========== 产品数据 ==========
const PRODUCTS = [
  // ============================================================
  // 一、高擎动力 — 人形机器人 (Mini Pi 系列)
  // ============================================================
  {
    id: "hightorque-mini-pi",
    name: "Mini Pi Bipedal Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 3500,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Entry Level",
    badgeType: "badge-new",
    tagline: "12 DOF · 50 cm tall · 9.7 kg · RK3588 CPU",
    description: "Entry-level bipedal gait experimental platform. Stands 50 cm tall when powered on, weighs 9.7 kg including battery. 12 full-body degrees of freedom with max joint torque of 21 Nm, equipped with 12 HTDW-5036-02-DNE motors. CE and FCC certified. Features OLED status display, CAN FD communication (1000 Hz), and pre-deployed ROS1 development environment with open SDK.",
    images: ["image/hightorque_wrc2025_p1_img1.jpeg"],
    specs: [
      { label: "Height", value: "50 cm" },
      { label: "Weight", value: "9.7 kg (with battery)" },
      { label: "Degrees of Freedom", value: "12 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE" },
      { label: "CPU", value: "RK3588" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Battery", value: "21.6 V, 4500 mAh, CE certified" },
      { label: "Development", value: "ROS1 + open SDK, MIT 5-parameter control" },
      { label: "Algorithm Support", value: "Humanoid Gym training framework" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/livelybot_pi_rl_baseline",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },
  {
    id: "hightorque-mini-pi-pro",
    name: "Mini Pi Pro Bipedal Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 6000,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Computing Upgrade",
    badgeType: "badge-hot",
    tagline: "12 DOF · NVIDIA Jetson Orin NX · 50 cm · Enhanced AI Computing",
    description: "Upgraded Mini Pi with NVIDIA Jetson Orin NX CPU for enhanced AI computing. Same 12 DOF bipedal platform with 50 cm height and 9.7 kg weight. Integrated ROS1 environment, open SDK, MIT 5-parameter adaptive controller, and Humanoid Gym training framework support.",
    images: ["image/hightorque_wrc2025_p2_img1.jpeg"],
    specs: [
      { label: "Height", value: "50 cm" },
      { label: "Weight", value: "9.7 kg (with battery)" },
      { label: "Degrees of Freedom", value: "12 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE" },
      { label: "CPU", value: "NVIDIA Jetson Orin NX" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Battery", value: "21.6 V, 4500 mAh, CE certified" },
      { label: "Development", value: "ROS1 + open SDK, MIT 5-parameter control" },
      { label: "Algorithm Support", value: "Humanoid Gym training framework" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/livelybot_pi_rl_baseline",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },
  {
    id: "hightorque-mini-pi-plus",
    name: "Mini Pi Plus Humanoid Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 5500,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Dual-Arm Operation",
    badgeType: "badge-hot",
    tagline: "22 DOF · 68 cm · 15.15 kg · 10 kg payload · Bionic dual-arm design",
    description: "Small humanoid robot experimental platform with bionic design. Stands 68 cm tall, weighs 15.15 kg with battery, 10 kg load capacity. 22 full-body DOF equipped with 12 HTDW-5036-02-DNE, 8 HTDW-4530-02-DNE and 2 HTDW-3532-02-DNE motors. Supports static standing, gait walking, dancing, and dual-arm manipulation.",
    images: ["image/mini-pi-des-1.jpg"],
    specs: [
      { label: "Height", value: "68 cm" },
      { label: "Weight", value: "15.15 kg (with battery)" },
      { label: "Payload Capacity", value: "10 kg" },
      { label: "Degrees of Freedom", value: "22 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE + 8 × HTDW-4530-02-DNE + 2 × HTDW-3532-02-DNE" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/Mini-Pi-Plus_BeyondMimic",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },
  {
    id: "hightorque-mini-pi-plus-pro",
    name: "Mini Pi Plus Pro Humanoid Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 7500,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Flagship Research",
    badgeType: "badge-hot",
    tagline: "22 DOF · 68 cm · NVIDIA Jetson Orin NX · Full bionic dual-arm platform",
    description: "Pro version of Mini Pi Plus with NVIDIA Jetson Orin NX for advanced AI computing. Bionic dual-arm design, 22 DOF, supports static standing, gait walking, dancing, dual-arm manipulation, and more. Pre-deployed development environment, ready out of the box.",
    images: ["image/mini-pi-plus-performance.png"],
    specs: [
      { label: "Height", value: "68 cm" },
      { label: "Weight", value: "15.15 kg (with battery)" },
      { label: "Payload Capacity", value: "10 kg" },
      { label: "Degrees of Freedom", value: "22 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE + 8 × HTDW-4530-02-DNE + 2 × HTDW-3532-02-DNE" },
      { label: "CPU", value: "NVIDIA Jetson Orin NX" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/Mini-Pi-Plus_BeyondMimic",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },

  // ============================================================
  // 二、高擎动力 — 机械臂
  // ============================================================
  {
    id: "hightorque-panthera-ht",
    name: "Panthera-HT 6-Axis Robotic Arm",
    category: "robot-arm",
    brand: "HighTorque",
    price: 1799,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Open-Source Arm",
    badgeType: "badge-hot",
    tagline: "6-Axis · Upright mounting · High-precision servo joints",
    description: "6-axis robotic arm with upright mounting structure. Designed for research, education, and light industrial applications. High-precision servo joints with dual absolute encoders, CAN FD communication, and open SDK support.",
    images: ["image/OIP.webp"],
    specs: [
      { label: "Axes", value: "6-Axis" },
      { label: "Mounting", value: "Upright" },
      { label: "Communication", value: "CAN FD" },
      { label: "Encoders", value: "Dual absolute encoders" },
      { label: "Development", value: "Open SDK, ROS compatible" },
    ],
    github: "https://github.com/HighTorque-Robotics",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },

  // ============================================================
  // 三、高擎动力 — 关节模组 (Planetary Joint Modules)
  // ============================================================
  {
    id: "hightorque-htdw-4438-30-ne",
    name: "HTDW-4438-30-NE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Standard",
    tagline: "44mm · 30:1 ratio · 2 Nm rated torque · 10 Nm stall torque",
    description: "Compact planetary joint module, 44mm footprint, 43.4mm height, 237g weight. Reduction ratio 30, rated torque 2 Nm, stall torque 10 Nm. CAN FD/CAN communication, 5 Mbps baud rate, 3 kHz control frequency.",
    images: ["image/HTDW-4438-30-NE.png"],
    specs: [
      { label: "Footprint", value: "44 × 44 mm" },
      { label: "Height", value: "43.4 mm" },
      { label: "Weight", value: "237 g" },
      { label: "Reduction Ratio", value: "30" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "2 Nm" },
      { label: "Stall Torque", value: "10 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "160 RPM" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
      { label: "Repeat Positioning Accuracy", value: "< 12 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-4438-30-ne-jc",
    name: "HTDW-4438-30-NE-JC Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 199,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Cross Roller Bearing",
    tagline: "44mm · Cross roller bearing · 30:1 ratio · 2 Nm rated torque",
    description: "Planetary joint module with cross roller bearing version. 44mm footprint, 44.9mm height, 237g. Same performance specs as HTDW-4438-30-NE but with enhanced bearing structure for higher radial load capacity.",
    images: ["image/HTDW-4438-30-NE-JC.png"],
    specs: [
      { label: "Footprint", value: "44 × 44 mm" },
      { label: "Height", value: "44.9 mm" },
      { label: "Weight", value: "237 g" },
      { label: "Reduction Ratio", value: "30" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "2 Nm" },
      { label: "Stall Torque", value: "10 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "160 RPM" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
      { label: "Bearing Type", value: "Cross roller bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-5022-02-dne",
    name: "HTDW-5022-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Standard",
    tagline: "50mm · 22:1 ratio · 3.5 Nm rated torque · 21 Nm stall torque",
    description: "50mm planetary joint module with 22:1 reduction ratio. Rated torque 3.5 Nm, stall torque 21 Nm, rated speed 82 RPM. Weighs 322g with 12-50.4V voltage range.",
    images: ["image/HTDW-5022-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "47.4 mm" },
      { label: "Weight", value: "322 g" },
      { label: "Reduction Ratio", value: "22" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "3.5 Nm" },
      { label: "Stall Torque", value: "21 Nm" },
      { label: "Rated Speed", value: "82 RPM" },
      { label: "No-load Speed", value: "123 RPM" },
      { label: "Rated Output Power", value: "30 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-5036-02-dne",
    name: "HTDW-5036-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Best Seller",
    badgeType: "badge-hot",
    tagline: "50mm · 36:1 ratio · 6 Nm rated torque · 30 Nm stall torque",
    description: "Core planetary joint module used in Mini Pi series robots. 50mm footprint, 36:1 ratio, 6 Nm rated torque, 30 Nm stall torque. The most commonly used module in HighTorque humanoid robots.",
    images: ["image/HTDW-5036-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "47.4 mm" },
      { label: "Weight", value: "323 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "6 Nm" },
      { label: "Stall Torque", value: "30 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "75 RPM" },
      { label: "Rated Output Power", value: "30 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "hightorque-htdw-5036-02-cne",
    name: "HTDW-5036-02-CNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 199,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Cross Roller Bearing",
    tagline: "50mm · Cross roller bearing · 36:1 · 6 Nm rated · 30 Nm stall",
    description: "Cross roller bearing version of HTDW-5036. Same 50mm footprint and 36:1 ratio with enhanced bearing for higher radial load capacity. Weighs 345g.",
    images: ["image/HTDW-5036-02-CNE.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "47.4 mm" },
      { label: "Weight", value: "345 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "6 Nm" },
      { label: "Stall Torque", value: "30 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "75 RPM" },
      { label: "Rated Output Power", value: "30 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross roller bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-6036-02-dne",
    name: "HTDW-6036-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 219,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "High Torque",
    tagline: "60mm · 36:1 · 10 Nm rated · 52 Nm stall · 565g",
    description: "60mm planetary joint module for higher torque applications. 10 Nm rated torque, 52 Nm stall torque. Suitable for larger humanoid robots and heavy-load scenarios.",
    images: ["image/HTDW-6036-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "60 × 60 mm" },
      { label: "Height", value: "56 mm" },
      { label: "Weight", value: "565 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "10 Nm" },
      { label: "Stall Torque", value: "52 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "60 RPM" },
      { label: "Rated Output Power", value: "52 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "15 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-6036-02-cne",
    name: "HTDW-6036-02-CNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 229,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "High Torque · Cross Roller",
    tagline: "60mm · Cross roller · 36:1 · 10 Nm rated · 52 Nm stall",
    description: "Cross roller bearing version of HTDW-6036. Enhanced radial load capacity with 570g weight. Same torque specs as DNE version.",
    images: ["image/HTDW-6036-02-CNE.png"],
    specs: [
      { label: "Footprint", value: "60 × 60 mm" },
      { label: "Height", value: "56 mm" },
      { label: "Weight", value: "570 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "10 Nm" },
      { label: "Stall Torque", value: "52 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "60 RPM" },
      { label: "Rated Output Power", value: "52 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "15 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross roller bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htpw-7507-02-dne",
    name: "HTPW-7507-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "High-Speed",
    tagline: "75mm · 7:1 ratio · 4 Nm rated · 12 Nm stall · 250 RPM",
    description: "High-speed planetary joint module with 7:1 reduction ratio. 4 Nm rated torque at 250 RPM rated speed. Suitable for applications requiring high speed and moderate torque.",
    images: ["image/HTPW-7507-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "75 × 75 mm" },
      { label: "Height", value: "35 mm" },
      { label: "Weight", value: "390 g" },
      { label: "Reduction Ratio", value: "7" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "4 Nm" },
      { label: "Stall Torque", value: "12 Nm" },
      { label: "Rated Speed", value: "250 RPM" },
      { label: "No-load Speed", value: "270 RPM" },
      { label: "Rated Output Power", value: "92 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "20 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-7535-02-cne",
    name: "HTDW-7535-02-CNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 309,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "High Power",
    badgeType: "badge-hot",
    tagline: "75mm · Cross roller · 35:1 · 18 Nm rated · 60 Nm stall",
    description: "High-power planetary joint module with cross roller bearing. 18 Nm rated torque, 60 Nm stall torque. 850g weight. Suitable for heavy-load humanoid robot joints.",
    images: ["image/HTDW-7535-02-CNE.png"],
    specs: [
      { label: "Footprint", value: "75 × 75 mm" },
      { label: "Height", value: "56 mm" },
      { label: "Weight", value: "850 g" },
      { label: "Reduction Ratio", value: "35" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "18 Nm" },
      { label: "Stall Torque", value: "60 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "60 RPM" },
      { label: "Rated Output Power", value: "94 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "20 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross roller bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htpu-6035-04-cne",
    name: "HTPU-6035-04-CNE Ultra-Thin Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 279,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Ultra-Thin",
    tagline: "115×61.9mm · 37mm height · 35:1 · 10 Nm rated · 558g",
    description: "Ultra-thin series joint module with crossed roller bearing. Only 37mm height, 558g weight. 10 Nm rated torque, 36 Nm peak torque. Ideal for space-constrained applications.",
    images: ["image/HTPU-6035-04-CNE.png"],
    specs: [
      { label: "Dimensions", value: "115 × 61.9 mm" },
      { label: "Height", value: "37 mm" },
      { label: "Weight", value: "558 g" },
      { label: "Reduction Ratio", value: "35" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "10 Nm" },
      { label: "Peak Torque", value: "36 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "Rated Output Power", value: "52 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Stall Current", value: "15 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross roller bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htpu-7033-04-cne",
    name: "HTPU-7033-04-CNE Ultra-Thin Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 339,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Ultra-Thin High Torque",
    tagline: "140.5×71.5mm · 33:1 · 20 Nm rated · 60 Nm peak · 808g",
    description: "Large ultra-thin joint module. 20 Nm rated torque, 60 Nm peak torque. 808g weight with 36.9mm height. Crossed roller bearing design for high precision.",
    images: ["image/HTPU-7033-04-CNE.png"],
    specs: [
      { label: "Dimensions", value: "140.5 × 71.5 mm" },
      { label: "Height", value: "36.9 mm" },
      { label: "Weight", value: "808 g" },
      { label: "Reduction Ratio", value: "33" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "20 Nm" },
      { label: "Peak Torque", value: "60 Nm" },
      { label: "Stall Torque", value: "50 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "48 RPM" },
      { label: "Rated Output Power", value: "84 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "20 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross roller bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htcp-4531-06-cyc",
    name: "HTCP-4531-06-CYC Hollow Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 259,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Hollow Cable Routing",
    tagline: "44mm · 31:1 · 2 Nm rated · 10 Nm stall · Hollow design",
    description: "Hollow joint module with 31:1 harmonic reduction. Hollow center for cable routing. 2 Nm rated torque, 10 Nm stall torque. Ideal for robot joints requiring internal wiring.",
    images: ["image/HTCP-4531-06-CYC.png"],
    specs: [
      { label: "Footprint", value: "44 × 44 mm" },
      { label: "Height", value: "44.9 mm" },
      { label: "Weight", value: "237 g" },
      { label: "Reduction Ratio", value: "31" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "2 Nm" },
      { label: "Stall Torque", value: "10 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "160 RPM" },
      { label: "Rated Output Power", value: "8.5 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Type", value: "Hollow (harmonic)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htcp-5031-06-cyc",
    name: "HTCP-5031-06-CYC Hollow Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 259,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Hollow Cable Routing",
    tagline: "50mm · 31:1 · 4 Nm rated · 16 Nm stall · Hollow design",
    description: "Larger hollow joint module with 4 Nm rated torque, 16 Nm stall torque. 50mm footprint, 385g weight. Hollow center for cable routing through robot joints.",
    images: ["image/HTCP-5031-06-CYC.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "53 mm" },
      { label: "Weight", value: "385 g" },
      { label: "Reduction Ratio", value: "31" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "4 Nm" },
      { label: "Stall Torque", value: "16 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "103 RPM" },
      { label: "Rated Output Power", value: "21 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Type", value: "Hollow (harmonic)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },

  // ============================================================
  // 四、高擎动力 — 配件
  // ============================================================
  {
    id: "hightorque-zed-mini-camera",
    name: "ZED Mini Vision Camera Upgrade",
    category: "accessory",
    brand: "HighTorque",
    price: 1000,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Vision Upgrade",
    tagline: "Depth range 0.1–15 m · 2K resolution · 100 fps max · For Orin version",
    description: "ZED Mini stereo camera upgrade for Mini Pi Plus Pro / Mini Hi Plus series (Orin version only). Depth sensing range 0.1–15 m, maximum output resolution 4416×1242 (2K) at 15 fps, maximum device frame rate 100 fps.",
    images: ["image/zed_mini_datasheet_page1_render.png"],
    specs: [
      { label: "Depth Sensing Range", value: "0.1–15 m" },
      { label: "Depth Field of View", value: "90° × 60° × 100°" },
      { label: "Max Output Resolution", value: "4416 × 1242 (2K)" },
      { label: "Frame Rate at 2K", value: "15 fps" },
      { label: "Max Device Frame Rate", value: "100 fps" },
      { label: "Physical Dimensions", value: "124.5 × 30.5 × 26.5 mm" },
      { label: "Compatibility", value: "Mini Pi Plus Pro (Orin version only)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-d435i-camera",
    name: "D435i Vision Camera Upgrade",
    category: "accessory",
    brand: "HighTorque",
    price: 600,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Vision Upgrade",
    tagline: "Depth range 0.3–3 m · 1280×720 · 90 fps max · For Hi series",
    description: "Intel RealSense D435i camera upgrade for Mini Hi Plus series (Orin version only). Depth sensing range 0.3–3 m, maximum output resolution 1280×720 at 30 fps, maximum device frame rate 90 fps.",
    images: ["image/d435i_quickstart_page1_render.png"],
    specs: [
      { label: "Depth Sensing Range", value: "0.3–3 m" },
      { label: "Depth Field of View", value: "85.2° × 58° × 94° (±3°)" },
      { label: "Max Output Resolution", value: "1280 × 720" },
      { label: "Frame Rate at 720p", value: "30 fps" },
      { label: "Max Device Frame Rate", value: "90 fps" },
      { label: "Physical Dimensions", value: "90 × 25 × 25 mm" },
      { label: "Compatibility", value: "Mini Hi Plus series (Orin version only)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-mini-pi-plus-gripper",
    name: "Mini Pi Plus Series Gripper",
    category: "accessory",
    brand: "HighTorque",
    price: 750,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Gripper Accessory",
    tagline: "Multi-DoF · 0–60° opening · ≤60 mm grasping width · Pair included",
    description: "Optional multi-degree-of-freedom gripper kit for Mini Pi Plus series. Includes two grippers and matching motors. Each gripper driven by one HTDW-4438-30-NE (updated HTDW-4530-02-DNE) and one HTDW-3532-02-DNE motor. Opening angle 0–60°, max grasping width ≤60 mm.",
    images: ["image/mini-pi-des-4.jpg"],
    specs: [
      { label: "Type", value: "Multi-DoF Gripper (pair)" },
      { label: "Gripper Opening Angle", value: "0–60°" },
      { label: "Max Grasping Width", value: "≤ 60 mm" },
      { label: "Motors per Gripper", value: "1 × HTDW-4530-02-DNE + 1 × HTDW-3532-02-DNE" },
      { label: "Quantity", value: "2 grippers + matching motors" },
      { label: "Compatibility", value: "Mini Pi Plus series" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },

  // ============================================================
  // 五、灵心巧手 — 灵巧手
  // ============================================================
  {
    id: "linker-hand-o6",
    name: "Linker Hand O6",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 6666,
    originalPrice: 8000,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "World's Lightest",
    badgeType: "badge-new",
    tagline: "6 Active + 5 Passive DoF · 370g · 50 kg max load · Linkage transmission",
    description: "The world's lightest high-performance dexterous hand, weighing only 370g with 50 kg maximum load capacity. Features 6 active + 5 passive DoF, self-developed high-torque servo motor modules with worm gear drive. ±0.2mm repeat positioning accuracy. Supports CAN and RS485 (Modbus) communication. Optional piezoresistive sensors and vision.",
    images: ["image/Linker Hand O6.png", "image/Linker Hand O6 2.png", "image/Linker Hand O6 3.png", "image/Linker Hand O6 4.png"],
    video: "image/Linker Hand O6_Power Showcase.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "11 (6 Active + 5 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "370 g" },
      { label: "Max Load", value: "50 kg" },
      { label: "Operating Voltage", value: "24V–48V" },
      { label: "Quiescent Current", value: "0.093 A @24V" },
      { label: "Repeat Positioning Accuracy", value: "< ±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "20 N" },
      { label: "Max Four-Finger Tip Force", value: "25 N" },
      { label: "Sensors", value: "Piezoresistive (optional), Vision (optional)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l6",
    name: "Linker Hand L6",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Entry Model",
    badgeType: "badge-new",
    tagline: "6 Active + 5 Passive DoF · 607g · 28 kg max load · 0.35s fast response",
    description: "High-precision biomimetic robotic hand for fast, accurate manipulation. 6 active + 5 passive DoF with rigid linkage transmission. Weighs only 607g, supports 28 kg max load. 0.35 second ultra-fast opening/closing response. ±0.2mm repeatability. CAN and RS485 (Modbus) communication.",
    images: ["image/Linker Hand L6.png", "image/Linker Hand L6 1.png", "image/Linker Hand L6 2.png", "image/Linker Hand L6 3.png"],
    video: "image/Linker Hand L6_Full Palm Tactile Pressure Sensing.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "11 (6 Active + 5 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "607 g" },
      { label: "Max Load", value: "28 kg" },
      { label: "Operating Voltage", value: "DC 24V ±10%" },
      { label: "Quiescent Current", value: "0.2 A" },
      { label: "Average Current (No-Load)", value: "0.6 A" },
      { label: "Max Current", value: "5.6 A" },
      { label: "Repeat Positioning Accuracy", value: "< ±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "12 N" },
      { label: "Max Four-Finger Tip Force", value: "15 N" },
      { label: "Opening/Closing Response", value: "0.35 s" },
      { label: "Sensors", value: "Piezoresistive (optional), Vision (optional)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l20-lite",
    name: "Linker Hand L20 Lite",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Best Value",
    badgeType: "badge-deal",
    tagline: "10 Active + 10 Passive DoF · 1216g · 20 kg max load · Multi-modal perception",
    description: "High-performance dexterous hand with 20 DoFs. Self-developed motors and linkage transmission. Configurable with cameras, electronic skin for full-range vision + touch perception. Edge-cloud architecture for one-click skill deployment. Supports ROS/QT environments with standard ROS plugins. Widely used in education, research, piano performance, and elderly care.",
    images: ["image/Linker Hand L20 Lite.png", "image/Linker Hand L20 Lite 1.png", "image/Linker Hand L20 Lite 2.png", "image/Linker Hand L20 Lite 3.png"],
    video: "image/Linker Hand L20 Lite_Crab Shuttle.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "20 (10 Active + 10 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "1216 g" },
      { label: "Max Load", value: "20 kg" },
      { label: "Operating Voltage", value: "24V–48V" },
      { label: "Quiescent Current", value: "0.3 A @24V" },
      { label: "Average Current (No-Load)", value: "0.374 A @24V" },
      { label: "Max Current", value: "1.82 A @24V" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "14 N" },
      { label: "Max Four-Finger Tip Force", value: "15 N" },
      { label: "Sensors", value: "Piezoresistive (standard), Vision (optional), Visual-Tactile (optional)" },
      { label: "Development", value: "ROS / QT, edge-cloud deployment" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "linker-hand-o20",
    name: "Linker Hand O20",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Industrial Grade",
    badgeType: "badge-hot",
    tagline: "16 DoF Direct Drive · 911g · 36 kg max load · CAN FD · Self-locking",
    description: "16-joint industrial-grade dexterous hand combining high-performance brushless motors with precision ball screw transmission. Rated payload 20 kg, 0.8s opening/closing time. Self-locking design maintains grasp with zero holding power consumption. CAN FD protocol (5 Mbps). Rated static current only 0.45 A for 24/7 continuous operation. Ideal for automotive assembly, aerospace, and hazardous-environment tasks.",
    images: ["image/Linker Hand O20.png", "image/Linker Hand O20 1.png", "image/Linker Hand O20 2.png", "image/Linker Hand O20 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "16 (Direct Drive)" },
      { label: "Transmission Method", value: "Direct Drive (Ball Screw)" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN FD (5 Mbps)" },
      { label: "Weight", value: "911 g" },
      { label: "Max Load", value: "36 kg" },
      { label: "Rated Payload", value: "20 kg" },
      { label: "Operating Voltage", value: "DC 24V ±10%" },
      { label: "Quiescent Current", value: "0.45 A" },
      { label: "Average Current (No-Load)", value: "1.1 A" },
      { label: "Max Current", value: "3.1 A" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "7 N" },
      { label: "Max Four-Finger Tip Force", value: "9 N" },
      { label: "Opening/Closing Time", value: "0.8 s" },
      { label: "Self-Locking", value: "Yes (zero holding power)" },
      { label: "Sensors", value: "Piezoresistive (standard)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l20",
    name: "Linker Hand L20",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Research Flagship",
    badgeType: "badge-hot",
    tagline: "16 Active + 5 Passive DoF · 21 joints · Linkage · Multi-modal perception",
    description: "21 DoF dexterous hand accurately simulating natural human hand grasping. Innovative linkage transmission and self-developed motors for high-precision movement. Supports force, vision, and tactile sensors for multi-modal perception. Edge-cloud architecture for one-click skill deployment. Widely used in education, industrial automation, household assistance, and elderly care.",
    images: ["image/Linker Hand L20.png", "image/Linker Hand L20 1.png", "image/Linker Hand L20 2.png", "image/Linker Hand L20 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "21 (16 Active + 5 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "1216 g" },
      { label: "Max Load", value: "20 kg" },
      { label: "Operating Voltage", value: "24V–48V" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "14 N" },
      { label: "Max Four-Finger Tip Force", value: "15 N" },
      { label: "Sensors", value: "Capacitive (optional), Piezoresistive (standard), Vision (optional), Visual-Tactile (optional)" },
      { label: "Development", value: "ROS / QT, edge-cloud deployment" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l25",
    name: "Linker Hand L25",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Advanced Model",
    tagline: "25 DoF · Approaching human hand level (human hand: 27 DOF)",
    description: "25 degrees of freedom, approaching the human hand's DOF level. Suitable for dexterous manipulation and fine operation research, bridging teaching and scientific research.",
    images: ["image/O.webp"],
    specs: [
      { label: "Degrees of Freedom", value: "25 DOF" },
      { label: "Drive Method", value: "Motor drive" },
      { label: "Perception", value: "Full visual-tactile perception" },
      { label: "Application", value: "Dexterous manipulation research" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "linker-hand-r30",
    name: "Linker Hand R30 Direct Drive",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "High Performance",
    badgeType: "badge-hot",
    tagline: "30 DOF Direct Drive · High dynamic response · Precision force control",
    description: "Direct-drive motor design for faster response and higher force control precision. 30 DOF provides ample motion flexibility for high-dynamic manipulation research tasks.",
    images: ["image/R-C.jpg"],
    specs: [
      { label: "Degrees of Freedom", value: "30 DOF" },
      { label: "Drive Method", value: "Direct-drive motor" },
      { label: "Perception", value: "Full visual-tactile perception" },
      { label: "Application", value: "High-dynamic manipulation · Teleoperation" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: false,
    featured: true,
  },
  {
    id: "linker-hand-l30",
    name: "Linker Hand L30",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Flagship",
    badgeType: "badge-hot",
    tagline: "21 DoF (17 Active + 4 Passive) · Tendon drive · ±0.20mm · 39 N grasping force",
    description: "Flagship bionic dexterous hand with advanced tendon drive and highly integrated mechatronic systems. 21 DoF (17 active + 4 passive) with independent thumb and four-finger control. ±0.20mm repeat positioning accuracy, 9 N peak fingertip force (four-finger), 6.5 N max thumb tip force, 39 N grasping force. 15 kg max load, 450°/s max movement speed. CAN FD communication.",
    images: ["image/Linker Hand L30.png", "image/Linker Hand L30 1.png", "image/Linker Hand L30 2.png", "image/Linker Hand L30 3.png"],
    video: "image/Linker Hand L30_Plugging and unplugging the power plug.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "21 (17 Active + 4 Passive)" },
      { label: "Transmission Method", value: "Bionic Tendon Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN FD (5 Mbps)" },
      { label: "Weight", value: "1192 g" },
      { label: "Max Load", value: "15 kg" },
      { label: "Operating Voltage", value: "DC 24V ±10%" },
      { label: "Quiescent Current", value: "0.16 A" },
      { label: "Max Current", value: "2.71 A" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "6.5 N" },
      { label: "Max Four-Finger Tip Force", value: "9 N" },
      { label: "Grasping Force", value: "39 N" },
      { label: "Max Movement Speed", value: "450°/s" },
      { label: "Sensors", value: "Piezoresistive (optional), Vision (optional)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },

  // ============================================================
  // 六、灵心巧手 — 遥操作设备
  // ============================================================
  {
    id: "linker-eg-exoskeleton-glove",
    name: "Linker EG Exoskeleton Glove",
    category: "teleoperation",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Teleoperation",
    badgeType: "badge-new",
    tagline: "15 joints captured · 16-bit encoders · ESP-NOW wireless · 50 Hz · 2h battery",
    description: "Exoskeleton glove for high-precision hand motion capture and assisted control. Powered by magnetic encoder technology with 0.005° capture accuracy. ESP-NOW wireless communication (indoor ≤20 m, outdoor ≤40 m). 50 Hz data frequency, 2-hour battery life with 500 mAh lithium battery. Type-C charging in ≤2 hours. Weighs only 190g per glove.",
    images: ["image/Linker EG Exoskeleton Glove.png", "image/Linker EG Exoskeleton Glove 1.png", "image/Linker EG Exoskeleton Glove 2.png", "image/Linker EG Exoskeleton Glove 3.png"],
    specs: [
      { label: "Model", value: "LEG1-02" },
      { label: "Number of Sensors", value: "15 (hand joints)" },
      { label: "Capture Accuracy", value: "0.005°" },
      { label: "Encoder", value: "16-bit high-precision" },
      { label: "Data Transmission", value: "ESP-NOW wireless" },
      { label: "Data Rate", value: "2 Mbps" },
      { label: "Transmission Range", value: "Indoor ≤20 m, Outdoor ≤40 m" },
      { label: "Data Frequency", value: "50 Hz" },
      { label: "Battery", value: "500 mAh lithium" },
      { label: "Battery Life", value: "2 hours continuous" },
      { label: "Charging", value: "Type-C, ≤2 hours full charge" },
      { label: "Weight", value: "190 g (single glove)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "linker-ta-teleoperated-arm",
    name: "Linker TA Teleoperated Arm",
    category: "teleoperation",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Teleoperation",
    badgeType: "badge-new",
    tagline: "14 DoF · 658mm single-arm span · 12-bit absolute encoder · 200 Hz · 1.4 kg",
    description: "14 DoF teleoperated arm that accurately maps human shoulder, elbow, and wrist motion trajectories. Chest-mounted wearable design with 12-bit high-resolution absolute encoders for sub-millimeter control precision. 200 Hz high-frequency communication with millisecond-level latency. Lightweight at ~1.4 kg with ergonomic design for extended use.",
    images: ["image/Linker TA Teleoperated Arm.png", "image/Linker TA Teleoperated Arm 1.png", "image/Linker TA Teleoperated Arm 2.png", "image/Linker TA Teleoperated Arm 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "14" },
      { label: "Single-Arm Span", value: "658 mm" },
      { label: "Wearing Method", value: "Chest-Mounted" },
      { label: "Communication Interface", value: "Type-C / CAN" },
      { label: "Weight", value: "1.53 kg / 1.4 kg" },
      { label: "Rated Voltage", value: "24V / 5V" },
      { label: "Encoder Type", value: "Absolute Encoder" },
      { label: "Encoder Resolution", value: "12-bit" },
      { label: "Communication Frequency", value: "200 Hz" },
      { label: "Latency", value: "Millisecond-level" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },

  // ============================================================
  // 七、灵心巧手 — 机械臂
  // ============================================================
  {
    id: "linker-arm-a7",
    name: "Linker Arm A7 Robotic Arm",
    category: "robot-arm",
    brand: "LinkerBot",
    price: null,
    currency: "USD",
    priceNote: "Ex-work Price",
    badge: "Lightweight Collaborative Arm",
    badgeType: "badge-new",
    tagline: "7 DoF · 600mm working radius · 3 kg payload · 5.9 kg weight · 360 RPM",
    description: "Commercial robotic arm for embodied intelligence and lightweight applications. 7 DoF architecture with large joint rotation ranges for flexible posture adjustment and complex trajectory planning. All-in-one joint design integrating motor, driver, and planetary reducer. Max joint speed 360 RPM. CAN/RS485 communication.",
    images: ["image/Linker Arm A7 Robotic Arm.png", "image/Linker Arm A7 Robotic Arm 1.png", "image/Linker Arm A7 Robotic Arm 2.png", "image/Linker Arm A7 Robotic Arm 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "7" },
      { label: "Weight", value: "5.9 kg" },
      { label: "Working Radius", value: "600 mm" },
      { label: "Rated Payload", value: "3 kg" },
      { label: "Operating Voltage", value: "48 V" },
      { label: "Communication Interface", value: "CAN / RS485" },
      { label: "Max Power", value: "500 W" },
      { label: "Max Joint Speed", value: "360 RPM" },
      { label: "Operating Temperature", value: "-20°C to 50°C" },
      { label: "Joint Design", value: "All-in-one (motor + driver + planetary reducer)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
];

// ========== 工具函数 ==========
function getFeaturedProducts(max) {
  return PRODUCTS.filter((p) => p.featured).slice(0, max || 3);
}

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

function formatPrice(price, currency, priceNote) {
  if (!price || price <= 0) return "Price on Inquiry";
  var formatted;
  if (currency === "USD") {
    formatted = "$" + price.toLocaleString("en-US");
  } else {
    formatted = "$" + price.toLocaleString("en-US");
  }
  if (priceNote) {
    formatted += " (" + priceNote + ")";
  }
  return formatted;
}
