/**
 * BionicHub 产品数据库 — 万物拟态 (WWNT) + 高擎动力 (HighTorque) + 灵心巧手 (LinkerBot)
 *
 * 数据来源：
 *   - WWNT 自研 OpenDuck Mini（www.wwntai.com/products/openduck-mini.html）
 *   - 高擎动力招标规格及报价表 (USD) — Ex-Works Price
 *   - 灵心巧手产品手册 20260513 英文版 — Ex-Works Price
 *   - 原 data.js 中灵心巧手的历史价格
 *
 * 分类体系：
 *   dexterous-hand    灵巧手
 *   humanoid-robot    人形机器人
 *   robot-arm         机械臂
 *   joint-module       关节模组
 *   accessory          配件
 *   teleoperation      遥操作设备
 */

// ========== Category Labels ==========
const CATEGORIES = {
  "dexterous-hand": "Dexterous Hands",
  "humanoid-robot": "Humanoid Robots",
  "robot-arm": "Robotic Arms",
  "joint-module": "Joint Modules",
  "accessory": "Accessories",
  "teleoperation": "Teleoperation Devices",
};

// ========== Brands ==========
const BRANDS = {
  "WWNT": "WWNT Robotics",
  "HighTorque": "HighTorque® Robotics",
  "LinkerBot": "LinkerBot",
};

// ========== Sort Options ==========
const SORT_OPTIONS = {
  "featured": "Sort By: Featured",
  "price-asc": "Price: Low to High",
  "price-desc": "Price: High to Low",
  "name": "Name: A-Z",
};

// ========== 产品数据 ==========
const PRODUCTS = [
  // ============================================================
  // 〇、万物拟态 (WWNT) — OpenDuck Mini 开源双足机器人
  // ============================================================
  {
    id: "wwnt-openduck-mini",
    name: "OpenDuck Mini Bipedal Robot",
    category: "humanoid-robot",
    brand: "WWNT",
    price: 369,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Fully Open Source",
    badgeType: "badge-new",
    tagline: "14+2 DOF | 42 cm Height | 3D-Printed | RL Walking on Raspberry Pi",
    description: "Open-source 3D-printed bipedal robot inspired by Disney BDX. Standing about 42 cm tall with 14+2 degrees of freedom, it walks out-of-the-box with a pre-trained reinforcement learning policy running on a Raspberry Pi Zero 2W. All 35+ 3D-printed structural parts (PLA/TPU), mechanical CAD, BOM, onboard software, MuJoCo simulation and RL policies are fully open source under Apache-2.0 (commercial use allowed). Shell color, coating, head styling and functions are deeply customizable — ideal for campus IP robots, robotics courses, reinforcement learning teaching, and Sim2Real research.",
    images: [
      "image/openduck-mini-hero.jpg",
      "image/openduck-mini-gallery-1.jpg",
      "image/openduck-mini-gallery-2.jpg",
    ],
    specs: [
      { label: "Height", value: "Approx. 42 cm (legs extended)" },
      { label: "Configuration", value: "Bipedal robot (inspired by Disney BDX)" },
      { label: "Degrees of Freedom", value: "14 + 2 (antennae)" },
      { label: "Actuators", value: "14 × Feetech STS3215 bus servos + 2 × SG90 micro servos" },
      { label: "Joint Layout", value: "5 DOF per leg (hip yaw/roll/pitch, knee, ankle); head pitch/yaw/roll + neck pitch; 2 antennae" },
      { label: "Controller", value: "Raspberry Pi Zero 2W (4× Cortex-A53 @ 1GHz, 512MB RAM)" },
      { label: "Sensors", value: "BNO055 9-axis IMU, foot contact switches, camera, microphone" },
      { label: "Power", value: "2S 18650 lithium battery pack (approx. 7.4V) with BMS protection" },
      { label: "Audio / Display", value: "MAX98357A I2S amplifier + speaker; dual-eye LED + projection expressions" },
      { label: "Structure", value: "35+ 3D-printed parts (PLA structural / TPU flexible), M3 heat-set inserts and bearings" },
      { label: "Control", value: "Xbox controller (Bluetooth): start/stop, acceleration, antennae, sound effects" },
      { label: "RL & Simulation", value: "Pre-trained ONNX walking policy, MuJoCo simulation, imitation learning pipeline" },
      { label: "Open Source License", value: "Apache-2.0 (commercial use allowed)" },
    ],
    github: "https://github.com/UnitClaw",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  // ============================================================
  // 一、高擎动力 — 人形机器人 (Mini Pi 系列)
  // ============================================================
  {
    id: "hightorque-mini-pi",
    name: "Mini Pi Bipedal Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 3500,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Entry-Level Bipedal Platform",
    badgeType: "badge-new",
    tagline: "12 DOF | 50 cm Height | 9.7 kg Weight | RK3588 Processor",
    description: "Entry-level bipedal gait experimental platform. Stands 50 cm tall when powered on, weighs 9.7 kg including battery. 12 full-body degrees of freedom with max joint torque of 21 Nm, equipped with 12 HTDW-5036-02-DNE motors. CE and FCC certified. Features OLED status display, CAN FD communication (1000 Hz), and pre-deployed ROS1 development environment with open SDK.",
    images: ["image/Mini Pi Bipedal Robot.png","image/45aa3d4da29151bcd5000d3064294212.png","image/36fa0b0b579bd9c2810ab49d2b3c8c71.png"],
    specs: [
      { label: "Height", value: "50 cm" },
      { label: "Weight", value: "9.7 kg (with battery)" },
      { label: "Degrees of Freedom", value: "12 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE" },
      { label: "Processor", value: "RK3588" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Battery", value: "21.6 V, 4500 mAh, CE certified" },
      { label: "Development", value: "ROS1 + open SDK, MIT 5-parameter control" },
      { label: "Algorithm Support", value: "Humanoid Gym training framework" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/livelybot_pi_rl_baseline",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },
  {
    id: "hightorque-mini-pi-pro",
    name: "Mini Pi Pro Bipedal Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 6000,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "High-Performance Compute Upgrade",
    badgeType: "badge-hot",
    tagline: "12 DOF | NVIDIA® Jetson Orin NX | 50 cm Height | Enhanced AI Computing",
    description: "Upgraded Mini Pi with NVIDIA® Jetson Orin NX Processor for enhanced AI computing. Same 12 DOF bipedal platform with 50 cm height and 9.7 kg weight. Integrated ROS1 environment, open SDK, MIT 5-parameter adaptive controller, and Humanoid Gym training framework support.",
    images: ["image/Mini Pi Bipedal Robot.png","image/45aa3d4da29151bcd5000d3064294212.png","image/36fa0b0b579bd9c2810ab49d2b3c8c71.png"],
    specs: [
      { label: "Height", value: "50 cm" },
      { label: "Weight", value: "9.7 kg (with battery)" },
      { label: "Degrees of Freedom", value: "12 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE" },
      { label: "Processor", value: "NVIDIA® Jetson Orin NX" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Battery", value: "21.6 V, 4500 mAh, CE certified" },
      { label: "Development", value: "ROS1 + open SDK, MIT 5-parameter control" },
      { label: "Algorithm Support", value: "Humanoid Gym training framework" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/livelybot_pi_rl_baseline",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },
  {
    id: "hightorque-mini-pi-plus",
    name: "Mini Pi Plus Humanoid Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 5500,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Dual Bionic Manipulator Platform",
    badgeType: "badge-hot",
    tagline: "22 DOF | 68 cm Height | 15.15 kg Weight | 10 kg Payload | Bionic Dual-Arm Design",
    description: "Small humanoid robot experimental platform with bionic design. Stands 68 cm tall, weighs 15.15 kg with battery, 10 kg load capacity. 22 full-body DOF equipped with 12 HTDW-5036-02-DNE, 8 HTDW-4530-02-DNE and 2 HTDW-3532-02-DNE motors. Supports static standing, gait walking, dancing, and dual-arm manipulation.",
    images: ["image/Mini Pi Plus Pro Humanoid Robot.png","image/mini-pi-des-1.jpg","image/5fb8ebc1d6fcfc556ff19ecc764cdeae.png","image/ba50d26882ccf91c5421d1eac964c75e.png"],
    specs: [
      { label: "Height", value: "68 cm" },
      { label: "Weight", value: "15.15 kg (with battery)" },
      { label: "Payload Capacity", value: "10 kg" },
      { label: "Degrees of Freedom", value: "22 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE + 8 × HTDW-4530-02-DNE + 2 × HTDW-3532-02-DNE" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/Mini-Pi-Plus_BeyondMimic",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },
  {
    id: "hightorque-mini-pi-plus-pro",
    name: "Mini Pi Plus Pro Humanoid Robot",
    category: "humanoid-robot",
    brand: "HighTorque",
    price: 7500,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Flagship Research-Grade Humanoid Robot",
    badgeType: "badge-hot",
    tagline: "22 DOF | 68 cm Height | NVIDIA® Jetson Orin NX | Full Bionic Dual-Arm Platform",
    description: "Pro version of Mini Pi Plus with NVIDIA® Jetson Orin NX for advanced AI computing. Bionic dual-arm design, 22 DOF, supports static standing, gait walking, dancing, dual-arm manipulation, and more. Pre-deployed development environment, ready out of the box.",
    images: ["image/Mini Pi Plus Pro Humanoid Robot.png","image/mini-pi-des-1.jpg","image/5fb8ebc1d6fcfc556ff19ecc764cdeae.png","image/ba50d26882ccf91c5421d1eac964c75e.png"],
    specs: [
      { label: "Height", value: "68 cm" },
      { label: "Weight", value: "15.15 kg (with battery)" },
      { label: "Payload Capacity", value: "10 kg" },
      { label: "Degrees of Freedom", value: "22 DOF" },
      { label: "Max Joint Torque", value: "21 Nm" },
      { label: "Motors", value: "12 × HTDW-5036-02-DNE + 8 × HTDW-4530-02-DNE + 2 × HTDW-3532-02-DNE" },
      { label: "Processor", value: "NVIDIA® Jetson Orin NX" },
      { label: "Communication", value: "CAN FD, 1000 Hz max" },
      { label: "Certifications", value: "CE, FCC (all motors)" },
    ],
    github: "https://github.com/HighTorque-Robotics/Mini-Pi-Plus_BeyondMimic",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
    competitions: "CRC Innovation & Creativity Competition (MOE Whitelist #51, National Class A); CRAIC Humanoid Solo & Group Dance",
  },

  // ============================================================
  // 二、高擎动力 — 机械臂
  // ============================================================
  {
    id: "hightorque-panthera-ht",
    name: "Panthera-HT 6-Axis Robotic Arm",
    category: "robot-arm",
    brand: "HighTorque",
    price: 1799,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Open-Source 6-Axis Robotic Arm",
    badgeType: "badge-hot",
    tagline: "6-Axis · Upright mounting · High-precision servo joints",
    description: "6-axis robotic arm with upright mounting structure. Designed for research, education, and light industrial applications. High-precision servo joints with dual absolute encoders, CAN FD communication, and open SDK support.",
    images: ["image/Panthera-HT 6-Axis Robotic Arm 1.png"],
    specs: [
      { label: "Axes", value: "6-Axis" },
      { label: "Mounting", value: "Upright" },
      { label: "Communication", value: "CAN FD" },
      { label: "Encoders", value: "Dual absolute encoders" },
      { label: "Development", value: "Open SDK, ROS compatible" },
    ],
    github: "https://github.com/HighTorque-Robotics",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },

  // ============================================================
  // 三、高擎动力 — 关节模组 (Planetary Joint Modules)
  // ============================================================
  {
    id: "hightorque-htdw-4438-30-ne",
    name: "HTDW-4438-30-NE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Standard Planetary Joint Module",
    tagline: "44 mm · 30:1 Gear Reduction Ratio · 2 Nm Rated Torque · 10 Nm Peak Stall Torque",
    description: "Compact planetary gear joint module, 44mm footprint, 43.4mm height, 237g weight. Reduction ratio 30, Continuous Rated Torque 2 Nm, Peak Stall Torque 10 Nm. CAN FD/CAN communication, 5 Mbps baud rate, 3 kHz control frequency.",
    images: ["image/HTDW-4438-30-NE.png"],
    specs: [
      { label: "Footprint", value: "44 × 44 mm" },
      { label: "Height", value: "43.4 mm" },
      { label: "Weight", value: "237 g" },
      { label: "Reduction Ratio", value: "30" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "2 Nm" },
      { label: "Stall Torque", value: "10 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "160 RPM" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
      { label: "Repeat Positioning Accuracy", value: "< 12 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-4438-30-ne-jc",
    name: "HTDW-4438-30-NE-JC Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 199,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Cross-Roller Bearing Joint Module",
    tagline: "44 mm · Cross-Roller Bearing · 30:1 Gear Reduction Ratio · 2 Nm Rated Torque",
    description: "Planetary joint module with cross-roller bearing version. 44mm footprint, 44.9mm height, 237g. Same performance specs as HTDW-4438-30-NE but with enhanced bearing structure for higher radial load capacity.",
    images: ["image/HTDW-4438-30-NE-JC.png"],
    specs: [
      { label: "Footprint", value: "44 × 44 mm" },
      { label: "Height", value: "44.9 mm" },
      { label: "Weight", value: "237 g" },
      { label: "Reduction Ratio", value: "30" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "2 Nm" },
      { label: "Stall Torque", value: "10 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "160 RPM" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
      { label: "Bearing Type", value: "Cross-Roller Bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-5022-02-dne",
    name: "HTDW-5022-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Standard Planetary Joint Module",
    tagline: "50 mm · 22:1 Gear Reduction Ratio · 3.5 Nm Rated Torque · 21 Nm Peak Stall Torque",
    description: "50mm planetary gear joint module with 22:1 gear reduction ratio. Rated torque 3.5 Nm, Peak Stall Torque 21 Nm, rated speed 82 RPM. Weighs 322g with 12-50.4V voltage range.",
    images: ["image/HTDW-5022-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "47.4 mm" },
      { label: "Weight", value: "322 g" },
      { label: "Reduction Ratio", value: "22" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "3.5 Nm" },
      { label: "Stall Torque", value: "21 Nm" },
      { label: "Rated Speed", value: "82 RPM" },
      { label: "No-load Speed", value: "123 RPM" },
      { label: "Rated Output Power", value: "30 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-5036-02-dne",
    name: "HTDW-5036-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Top-Selling Planetary Joint Module",
    badgeType: "badge-hot",
    tagline: "50 mm · 36:1 Gear Reduction Ratio · 6 Nm Rated Torque · 30 Nm Peak Stall Torque",
    description: "Core planetary gear joint module used in Mini Pi series robots. 50mm footprint, 36:1 Gear Reduction Ratio, 6 Nm Continuous Rated Torque, 30 Nm Peak Stall Torque. The most commonly used module in HighTorque humanoid robots.",
    images: ["image/HTDW-5036-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "47.4 mm" },
      { label: "Weight", value: "323 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "6 Nm" },
      { label: "Stall Torque", value: "30 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "75 RPM" },
      { label: "Rated Output Power", value: "30 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "hightorque-htdw-5036-02-cne",
    name: "HTDW-5036-02-CNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 199,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Cross-Roller Bearing Joint Module",
    tagline: "50 mm · Cross-Roller Bearing · 36:1 Gear Reduction · 6 Nm Rated · 30 Nm Peak Stall",
    description: "Cross-Roller Bearing version of HTDW-5036. Same 50mm footprint and 36:1 Gear Reduction Ratio with enhanced bearing for higher radial load capacity. Weighs 345g.",
    images: ["image/HTDW-5036-02-CNE.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "47.4 mm" },
      { label: "Weight", value: "345 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "6 Nm" },
      { label: "Stall Torque", value: "30 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "75 RPM" },
      { label: "Rated Output Power", value: "30 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross-Roller Bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-6036-02-dne",
    name: "HTDW-6036-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 219,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "High-Torque Joint Module",
    tagline: "60 mm · 36:1 Gear Reduction · 10 Nm Rated · 52 Nm Peak Stall · 565 g",
    description: "60mm planetary gear joint module for higher torque applications. 10 Nm Continuous Rated Torque, 52 Nm Peak Stall Torque. Suitable for larger humanoid robots and heavy-load scenarios.",
    images: ["image/HTDW-6036-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "60 × 60 mm" },
      { label: "Height", value: "56 mm" },
      { label: "Weight", value: "565 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "10 Nm" },
      { label: "Stall Torque", value: "52 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "60 RPM" },
      { label: "Rated Output Power", value: "52 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "15 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-6036-02-cne",
    name: "HTDW-6036-02-CNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 229,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "High-Torque Cross-Roller Bearing Joint Module",
    tagline: "60 mm · Cross-Roller · 36:1 Gear Reduction · 10 Nm Rated · 52 Nm Peak Stall",
    description: "Cross-Roller Bearing version of HTDW-6036. Enhanced radial load capacity with 570g weight. Same torque specs as DNE version.",
    images: ["image/HTDW-6036-02-CNE.png"],
    specs: [
      { label: "Footprint", value: "60 × 60 mm" },
      { label: "Height", value: "56 mm" },
      { label: "Weight", value: "570 g" },
      { label: "Reduction Ratio", value: "36" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "10 Nm" },
      { label: "Stall Torque", value: "52 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "60 RPM" },
      { label: "Rated Output Power", value: "52 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "15 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross-Roller Bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htpw-7507-02-dne",
    name: "HTPW-7507-02-DNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 189,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "High-Speed Planetary Joint Module",
    tagline: "75 mm · 7:1 Gear Reduction Ratio · 4 Nm Rated · 12 Nm Peak Stall · 250 RPM",
    description: "High-speed planetary gear joint module with 7:1 gear reduction ratio. 4 Nm Continuous Rated Torque at 250 RPM rated speed. Suitable for applications requiring high speed and moderate torque.",
    images: ["image/HTPW-7507-02-DNE.png"],
    specs: [
      { label: "Footprint", value: "75 × 75 mm" },
      { label: "Height", value: "35 mm" },
      { label: "Weight", value: "390 g" },
      { label: "Reduction Ratio", value: "7" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "4 Nm" },
      { label: "Stall Torque", value: "12 Nm" },
      { label: "Rated Speed", value: "250 RPM" },
      { label: "No-load Speed", value: "270 RPM" },
      { label: "Rated Output Power", value: "92 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "20 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Backlash", value: "< 10 arcmin" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htdw-7535-02-cne",
    name: "HTDW-7535-02-CNE Planetary Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 309,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "High-Power Planetary Joint Module",
    badgeType: "badge-hot",
    tagline: "75 mm · Cross-Roller · 35:1 Gear Reduction · 18 Nm Rated · 60 Nm Peak Stall",
    description: "High-power planetary gear joint module with cross-roller bearing. 18 Nm Continuous Rated Torque, 60 Nm Peak Stall Torque. 850g weight. Suitable for heavy-load humanoid robot joints.",
    images: ["image/HTDW-7535-02-CNE.png"],
    specs: [
      { label: "Footprint", value: "75 × 75 mm" },
      { label: "Height", value: "56 mm" },
      { label: "Weight", value: "850 g" },
      { label: "Reduction Ratio", value: "35" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "18 Nm" },
      { label: "Stall Torque", value: "60 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "60 RPM" },
      { label: "Rated Output Power", value: "94 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "20 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross-Roller Bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htpu-6035-04-cne",
    name: "HTPU-6035-04-CNE Ultra-Thin Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 279,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Ultra-Thin Integrated Joint Module",
    tagline: "115 × 61.9 mm · 37 mm Height · 35:1 Gear Reduction · 10 Nm Rated · 558 g",
    description: "Ultra-thin series joint module with cross-roller bearing. Only 37mm height, 558g weight. 10 Nm Continuous Rated Torque, 36 Nm peak torque. Ideal for space-constrained applications.",
    images: ["image/HTPU-6035-04-CNE.png"],
    specs: [
      { label: "Dimensions", value: "115 × 61.9 mm" },
      { label: "Height", value: "37 mm" },
      { label: "Weight", value: "558 g" },
      { label: "Reduction Ratio", value: "35" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "10 Nm" },
      { label: "Peak Torque", value: "36 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "Rated Output Power", value: "52 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Stall Current", value: "15 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross-Roller Bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htpu-7033-04-cne",
    name: "HTPU-7033-04-CNE Ultra-Thin Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 339,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Ultra-Thin High-Torque Integrated Joint Module",
    tagline: "140.5 × 71.5 mm · 33:1 Gear Reduction · 20 Nm Rated · 60 Nm Peak · 808 g",
    description: "Large ultra-thin joint module. 20 Nm Continuous Rated Torque, 60 Nm peak torque. 808g weight with 36.9mm height. Crossed roller bearing design for high precision.",
    images: ["image/HTPU-7033-04-CNE.png"],
    specs: [
      { label: "Dimensions", value: "140.5 × 71.5 mm" },
      { label: "Height", value: "36.9 mm" },
      { label: "Weight", value: "808 g" },
      { label: "Reduction Ratio", value: "33" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "20 Nm" },
      { label: "Peak Torque", value: "60 Nm" },
      { label: "Stall Torque", value: "50 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "48 RPM" },
      { label: "Rated Output Power", value: "84 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "20 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Bearing Type", value: "Cross-Roller Bearing" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htcp-4531-06-cyc",
    name: "HTCP-4531-06-CYC Hollow Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 259,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Hollow Shaft Cable-Routing Joint Module",
    tagline: "44 mm · 31:1 Gear Reduction · 2 Nm Rated · 10 Nm Peak Stall · Hollow Design",
    description: "Hollow joint module with 31:1 harmonic reduction. Hollow center for cable routing. 2 Nm Continuous Rated Torque, 10 Nm Peak Stall Torque. Ideal for robot joints requiring internal wiring.",
    images: ["image/HTCP-4531-06-CYC.png"],
    specs: [
      { label: "Footprint", value: "44 × 44 mm" },
      { label: "Height", value: "44.9 mm" },
      { label: "Weight", value: "237 g" },
      { label: "Reduction Ratio", value: "31" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "2 Nm" },
      { label: "Stall Torque", value: "10 Nm" },
      { label: "Rated Speed", value: "40 RPM" },
      { label: "No-load Speed", value: "160 RPM" },
      { label: "Rated Output Power", value: "8.5 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Type", value: "Hollow (harmonic)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-htcp-5031-06-cyc",
    name: "HTCP-5031-06-CYC Hollow Joint Module",
    category: "joint-module",
    brand: "HighTorque",
    price: 259,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Hollow Shaft Cable-Routing Joint Module",
    tagline: "50 mm · 31:1 Gear Reduction · 4 Nm Rated · 16 Nm Peak Stall · Hollow Design",
    description: "Larger hollow joint module with 4 Nm Continuous Rated Torque, 16 Nm Peak Stall Torque. 50mm footprint, 385g weight. Hollow center for cable routing through robot joints.",
    images: ["image/HTCP-5031-06-CYC.png"],
    specs: [
      { label: "Footprint", value: "50 × 50 mm" },
      { label: "Height", value: "53 mm" },
      { label: "Weight", value: "385 g" },
      { label: "Reduction Ratio", value: "31" },
      { label: "Rated Voltage", value: "24 V" },
      { label: "Rated Torque", value: "4 Nm" },
      { label: "Stall Torque", value: "16 Nm" },
      { label: "Rated Speed", value: "50 RPM" },
      { label: "No-load Speed", value: "103 RPM" },
      { label: "Rated Output Power", value: "21 W" },
      { label: "Voltage Range", value: "12–50.4 V" },
      { label: "Peak Current", value: "10 A" },
      { label: "Encoder", value: "14-bit input + 14-bit output" },
      { label: "Communication", value: "CAN FD / CAN, 5 Mbps" },
      { label: "Control Frequency", value: "3 kHz" },
      { label: "Type", value: "Hollow (harmonic)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },

  // ============================================================
  // 四、高擎动力 — 配件
  // ============================================================
  {
    id: "hightorque-zed-mini-camera",
    name: "ZED Mini Vision Camera Upgrade",
    category: "accessory",
    brand: "HighTorque",
    price: 1000,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Depth Vision Camera Upgrade Kit",
    tagline: "Depth range 0.1–15 m · 2K resolution · 100 fps max · For Orin version",
    description: "ZED Mini stereo camera upgrade for Mini Pi Plus Pro / Mini Hi Plus series (Orin version only). Depth sensing range 0.1–15 m, maximum output resolution 4416×1242 (2K) at 15 fps, maximum device frame rate 100 fps.",
    images: ["image/zed_mini_datasheet_page1_render.png"],
    specs: [
      { label: "Depth Sensing Range", value: "0.1–15 m" },
      { label: "Depth Field of View", value: "90° × 60° × 100°" },
      { label: "Max Output Resolution", value: "4416 × 1242 (2K)" },
      { label: "Frame Rate at 2K", value: "15 fps" },
      { label: "Max Device Frame Rate", value: "100 fps" },
      { label: "Physical Dimensions", value: "124.5 × 30.5 × 26.5 mm" },
      { label: "Compatibility", value: "Mini Pi Plus Pro (Orin version only)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-d435i-camera",
    name: "D435i Vision Camera Upgrade",
    category: "accessory",
    brand: "HighTorque",
    price: 600,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Depth Vision Camera Upgrade Kit",
    tagline: "Depth range 0.3–3 m · 1280×720 · 90 fps max · For Hi series",
    description: "Intel RealSense D435i camera upgrade for Mini Hi Plus series (Orin version only). Depth sensing range 0.3–3 m, maximum output resolution 1280×720 at 30 fps, maximum device frame rate 90 fps.",
    images: ["image/d435i_quickstart_page1_render.png"],
    specs: [
      { label: "Depth Sensing Range", value: "0.3–3 m" },
      { label: "Depth Field of View", value: "85.2° × 58° × 94° (±3°)" },
      { label: "Max Output Resolution", value: "1280 × 720" },
      { label: "Frame Rate at 720p", value: "30 fps" },
      { label: "Max Device Frame Rate", value: "90 fps" },
      { label: "Physical Dimensions", value: "90 × 25 × 25 mm" },
      { label: "Compatibility", value: "Mini Hi Plus series (Orin version only)" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "hightorque-mini-pi-plus-gripper",
    name: "Mini Pi Plus Series Gripper",
    category: "accessory",
    brand: "HighTorque",
    price: 750,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Robotic Gripper Accessory Kit",
    tagline: "Multi-DOF · 0–60° Gripper Opening Stroke · Max 60 mm Grasping Width · Pair Included",
    description: "Optional multi-degree-of-freedom gripper kit for Mini Pi Plus series. Includes two grippers and matching motors. Each gripper driven by one HTDW-4438-30-NE (updated HTDW-4530-02-DNE) and one HTDW-3532-02-DNE motor. Gripper opening stroke 0–60°, Maximum grasping width 60 mm.",
    images: ["image/mini-pi-des-4.jpg"],
    specs: [
      { label: "Type", value: "Multi-DOF Gripper (pair)" },
      { label: "Gripper Opening Angle", value: "0–60°" },
      { label: "Max Grasping Width", value: "≤ 60 mm" },
      { label: "Motors per Gripper", value: "1 × HTDW-4530-02-DNE + 1 × HTDW-3532-02-DNE" },
      { label: "Quantity", value: "2 grippers + matching motors" },
      { label: "Compatibility", value: "Mini Pi Plus series" },
    ],
    github: "",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },

  // ============================================================
  // 五、灵心巧手 — 灵巧手
  // ============================================================
  {
    id: "linker-hand-o30",
    name: "Linker Hand O30",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 7499,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "20 DOF Full Active",
    badgeType: "badge-new",
    tagline: "20 Active DOF · 730 g · 30 kg Max Load · Direct Drive · 0.8 s Open-Close Cycle",
    description: "Linker Hand O30 is a 20-DOF fully active direct-drive dexterous hand for advanced manipulation. Enables precise pinching, stable grasping, and coordinated multi-finger control with high power density and lightweight integration. Designed for embodied AI, reinforcement learning, dexterous manipulation development, and high-precision manufacturing.",
    images: ["image/Linker Hand O30.png", "image/Linker Hand O30 2.png", "image/Linker Hand O30 3.png"],
    video: "image/Linker Hand O30_Tactile Perception.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "20 Active DOF" },
      { label: "Drive Method", value: "Direct Drive" },
      { label: "Communication Frequency", value: "500 Hz" },
      { label: "Communication Interface", value: "CAN / CAN FD" },
      { label: "Weight", value: "730 g" },
      { label: "Max Load", value: "30 kg" },
      { label: "Operating Voltage", value: "DC 24V–48V" },
      { label: "Static Current", value: "0.4 A @24V" },
      { label: "Average No-Load Motion Current", value: "1.1 A @24V" },
      { label: "Max Power", value: "150 W" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Opening / Closing Time", value: "0.8 s" },
      { label: "Thumb Fingertip Force", value: "24 N" },
      { label: "Four-Finger Lateral Pinch Force", value: "30 N" },
      { label: "Five-Finger Grasping Force", value: "70 N" },
      { label: "Thumb Rotation Range", value: "0.63 rad (36°)" },
      { label: "Four-Finger Bending Angle", value: "1.84 rad (105.315°)" },
      { label: "Thumb Lateral Swing Speed", value: "1.8718 rad/s (107.249°/s)" },
      { label: "Four-Finger Bending Speed", value: "2.3871 rad/s (136.77°/s)" },
      { label: "Thumb Bending Speed", value: "2.3134 rad/s (132.55°/s)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-o6",
    name: "Linker Hand O6",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 999,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "World’s Lightweight Dexterous Robotic Hand",
    badgeType: "badge-new",
    tagline: "6 Active + 5 Passive DOF · 370 g · 50 kg Maximum Payload · Linkage-Driven Transmission",
    description: "The world's lightest high-performance dexterous hand, weighing only 370g with 50 kg maximum load capacity. Features 6 active + 5 passive DOF, self-developed high-torque servo motor modules with worm gear drive. ±0.2mm repeat positioning accuracy. Supports CAN and RS485 (Modbus) communication. Optional piezoresistive sensors and vision.",
    images: ["image/Linker Hand O6.png", "image/Linker Hand O6 2.png", "image/Linker Hand O6 3.png", "image/Linker Hand O6 4.png"],
    video: "image/Linker Hand O6_Power Showcase.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "11 (6 Active + 5 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "370 g" },
      { label: "Max Load", value: "50 kg" },
      { label: "Operating Voltage", value: "24V–48V" },
      { label: "Quiescent Current", value: "0.093 A @24V" },
      { label: "Repeat Positioning Accuracy", value: "< ±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "20 N" },
      { label: "Max Four-Finger Tip Force", value: "25 N" },
      { label: "Sensors", value: "Piezoresistive (optional), Vision (optional)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l6",
    name: "Linker Hand L6",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 2999,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Entry Model",
    badgeType: "badge-new",
    tagline: "6 Active + 5 Passive DOF · 607 g · 28 kg Maximum Payload · 0.35 s Rapid Dynamic Response",
    description: "High-precision biomimetic robotic hand for fast, accurate manipulation. 6 active + 5 passive DOF with rigid linkage-driven transmission. Weighs only 607g, supports 28 kg Maximum Payload. 0.35 s rapid dynamic response. ±0.2mm repeatability. CAN and RS485 (Modbus) communication.",
    images: ["image/Linker Hand L6.png", "image/Linker Hand L6 1.png", "image/Linker Hand L6 2.png", "image/Linker Hand L6 3.png"],
    video: "image/Linker Hand L6_Full Palm Tactile Pressure Sensing.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "11 (6 Active + 5 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "607 g" },
      { label: "Max Load", value: "28 kg" },
      { label: "Operating Voltage", value: "DC 24V ±10%" },
      { label: "Quiescent Current", value: "0.2 A" },
      { label: "Average Current (No-Load)", value: "0.6 A" },
      { label: "Max Current", value: "5.6 A" },
      { label: "Repeat Positioning Accuracy", value: "< ±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "12 N" },
      { label: "Max Four-Finger Tip Force", value: "15 N" },
      { label: "Opening/Closing Response", value: "0.35 s" },
      { label: "Sensors", value: "Piezoresistive (optional), Vision (optional)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l20-lite",
    name: "Linker Hand L20 Lite",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 2999,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Cost-Optimized Research Hand",
    badgeType: "badge-deal",
    tagline: "10 Active + 10 Passive DOF · 1216 g · 20 kg Maximum Payload · Multi-Modal Tactile & Kinesthetic Perception",
    description: "High-performance dexterous hand with 20 DOF. Self-developed motors and linkage-driven transmission. Configurable with cameras, electronic skin for full-range vision + touch perception. Edge-cloud architecture for one-click skill deployment. Supports ROS/QT environments with standard ROS plugins. Widely used in education, research, piano performance, and elderly care.",
    images: ["image/Linker Hand L20 Lite.png", "image/Linker Hand L20 Lite 1.png", "image/Linker Hand L20 Lite 2.png", "image/Linker Hand L20 Lite 3.png"],
    video: "image/Linker Hand L20 Lite_Crab Shuttle.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "20 (10 Active + 10 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "1216 g" },
      { label: "Max Load", value: "20 kg" },
      { label: "Operating Voltage", value: "24V–48V" },
      { label: "Quiescent Current", value: "0.3 A @24V" },
      { label: "Average Current (No-Load)", value: "0.374 A @24V" },
      { label: "Max Current", value: "1.82 A @24V" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "14 N" },
      { label: "Max Four-Finger Tip Force", value: "15 N" },
      { label: "Sensors", value: "Piezoresistive (standard), Vision (optional), Visual-Tactile (optional)" },
      { label: "Development", value: "ROS / QT, edge-cloud deployment" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "linker-hand-o20",
    name: "Linker Hand O20",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 2999,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Industrial-Grade Dexterous Hand",
    badgeType: "badge-hot",
    tagline: "16 DOF Direct-Drive · 911 g · 36 kg Maximum Payload · CAN FD · Integrated Self-Locking",
    description: "16-joint industrial-grade dexterous hand combining high-performance brushless motors with precision ball screw transmission. Rated payload 20 kg, 0.8s opening/closing time. Self-locking design maintains grasp with zero holding power consumption. CAN FD protocol (5 Mbps). Rated static current only 0.45 A for 24/7 continuous operation. Ideal for automotive assembly, aerospace, and hazardous-environment tasks.",
    images: ["image/Linker Hand O20.png", "image/Linker Hand O20 1.png", "image/Linker Hand O20 2.png", "image/Linker Hand O20 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "16 (Direct Drive)" },
      { label: "Transmission Method", value: "Direct Drive (Ball Screw)" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN FD (5 Mbps)" },
      { label: "Weight", value: "911 g" },
      { label: "Max Load", value: "36 kg" },
      { label: "Rated Payload", value: "20 kg" },
      { label: "Operating Voltage", value: "DC 24V ±10%" },
      { label: "Quiescent Current", value: "0.45 A" },
      { label: "Average Current (No-Load)", value: "1.1 A" },
      { label: "Max Current", value: "3.1 A" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "7 N" },
      { label: "Max Four-Finger Tip Force", value: "9 N" },
      { label: "Opening/Closing Time", value: "0.8 s" },
      { label: "Self-Locking", value: "Yes (zero holding power)" },
      { label: "Sensors", value: "Piezoresistive (standard)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
  {
    id: "linker-hand-l20",
    name: "Linker Hand L20",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 7499,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Flagship Research Dexterous Hand",
    badgeType: "badge-hot",
    tagline: "16 Active + 5 Passive DOF · 21 Joints · Linkage-Driven · Multi-Modal Tactile & Kinesthetic Perception",
    description: "21 DOF dexterous hand accurately simulating natural human hand grasping. Innovative linkage-driven transmission and self-developed motors for high-precision movement. Supports force, vision, and tactile sensors for multi-modal perception. Edge-cloud architecture for one-click skill deployment. Widely used in education, industrial automation, household assistance, and elderly care.",
    images: ["image/Linker Hand L20.png", "image/Linker Hand L20 1.png", "image/Linker Hand L20 2.png", "image/Linker Hand L20 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "21 (16 Active + 5 Passive)" },
      { label: "Transmission Method", value: "Linkage Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN / RS485" },
      { label: "Weight", value: "1216 g" },
      { label: "Max Load", value: "20 kg" },
      { label: "Operating Voltage", value: "24V–48V" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "14 N" },
      { label: "Max Four-Finger Tip Force", value: "15 N" },
      { label: "Sensors", value: "Capacitive (optional), Piezoresistive (standard), Vision (optional), Visual-Tactile (optional)" },
      { label: "Development", value: "ROS / QT, edge-cloud deployment" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },

  {
    id: "linker-hand-l30",
    name: "Linker Hand L30",
    category: "dexterous-hand",
    brand: "LinkerBot",
    price: 14999,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Flagship Tendon-Driven Robotic Hand",
    badgeType: "badge-hot",
    tagline: "21 DOF (17 Active + 4 Passive) · Tendon-Driven · ±0.20 mm · 39 N Grasping Payload Force",
    description: "Flagship bionic dexterous hand with advanced tendon-driven and highly integrated mechatronic systems. 21 DOF (17 active + 4 passive) with independent thumb and four-finger control. ±0.20 mm repeat positioning accuracy, 9 N peak fingertip force (four-finger), 6.5 N max thumb tip force, 39 N Grasping Payload Force. 15 kg Maximum Payload, 450°/s max movement speed. CAN FD communication.",
    images: ["image/Linker Hand L30.png", "image/Linker Hand L30 1.png", "image/Linker Hand L30 2.png", "image/Linker Hand L30 3.png"],
    video: "image/Linker Hand L30_Plugging and unplugging the power plug.mp4",
    specs: [
      { label: "Degrees of Freedom", value: "21 (17 Active + 4 Passive)" },
      { label: "Transmission Method", value: "Bionic Tendon Drive" },
      { label: "Drive Method", value: "Self-Developed Joint Module" },
      { label: "Control Interface", value: "CAN FD (5 Mbps)" },
      { label: "Weight", value: "1192 g" },
      { label: "Max Load", value: "15 kg" },
      { label: "Operating Voltage", value: "DC 24V ±10%" },
      { label: "Quiescent Current", value: "0.16 A" },
      { label: "Max Current", value: "2.71 A" },
      { label: "Repeat Positioning Accuracy", value: "±0.20 mm" },
      { label: "Max Thumb Tip Force", value: "6.5 N" },
      { label: "Max Four-Finger Tip Force", value: "9 N" },
      { label: "Grasping Force", value: "39 N" },
      { label: "Max Movement Speed", value: "450°/s" },
      { label: "Sensors", value: "Piezoresistive (optional), Vision (optional)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: true,
  },
   

  // ============================================================
  // 六、灵心巧手 — 遥操作设备
  // ============================================================
  {
    id: "linker-eg-exoskeleton-glove",
    name: "Linker EG Exoskeleton Glove",
    category: "teleoperation",
    brand: "LinkerBot",
    price: 1499,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Master Teleoperation Exoskeleton Glove",
    badgeType: "badge-new",
    tagline: "15 joints captured · 16-bit encoders · ESP-NOW wireless · 50 Hz · 2h battery",
    description: "Exoskeleton glove for high-precision hand motion capture and assisted control. Powered by magnetic encoder technology with 0.005° capture accuracy. ESP-NOW wireless communication (indoor ≤20 m, outdoor ≤40 m). 50 Hz data frequency, 2-hour battery life with 500 mAh lithium battery. Type-C charging in ≤2 hours. Weighs only 190g per glove.",
    images: ["image/Linker EG Exoskeleton Glove.png", "image/Linker EG Exoskeleton Glove 1.png", "image/Linker EG Exoskeleton Glove 2.png", "image/Linker EG Exoskeleton Glove 3.png"],
    specs: [
      { label: "Model", value: "LEG1-02" },
      { label: "Number of Sensors", value: "15 (hand joints)" },
      { label: "Capture Accuracy", value: "0.005°" },
      { label: "Encoder", value: "16-bit high-precision" },
      { label: "Data Transmission", value: "ESP-NOW wireless" },
      { label: "Data Rate", value: "2 Mbps" },
      { label: "Transmission Range", value: "Indoor ≤20 m, Outdoor ≤40 m" },
      { label: "Data Frequency", value: "50 Hz" },
      { label: "Battery", value: "500 mAh lithium" },
      { label: "Battery Life", value: "2 hours continuous" },
      { label: "Charging", value: "Type-C, ≤2 hours full charge" },
      { label: "Weight", value: "190 g (single glove)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
  {
    id: "linker-ta-teleoperated-arm",
    name: "Linker TA Teleoperated Arm",
    category: "teleoperation",
    brand: "LinkerBot",
    price: 1499,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Master Teleop Arm",
    badgeType: "badge-new",
    tagline: "14 DOF · 658 mm Single-Arm Reach Span · 12-bit Absolute Encoder · 200 Hz · 1.4 kg",
    description: "14 DOF teleoperated arm that accurately maps human shoulder, elbow, and wrist motion trajectories. Chest-mounted wearable design with 12-bit high-resolution absolute encoders for sub-millimeter control precision. 200 Hz high-frequency communication with millisecond-level latency. Lightweight at ~1.4 kg with ergonomic design for extended use.",
    images: ["image/Linker TA Teleoperated Arm.png", "image/Linker TA Teleoperated Arm 1.png", "image/Linker TA Teleoperated Arm 2.png", "image/Linker TA Teleoperated Arm 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "14" },
      { label: "Single-Arm Span", value: "658 mm" },
      { label: "Wearing Method", value: "Chest-Mounted" },
      { label: "Communication Interface", value: "Type-C / CAN" },
      { label: "Weight", value: "1.53 kg / 1.4 kg" },
      { label: "Rated Voltage", value: "24V / 5V" },
      { label: "Encoder Type", value: "Absolute Encoder" },
      { label: "Encoder Resolution", value: "12-bit" },
      { label: "Communication Frequency", value: "200 Hz" },
      { label: "Latency", value: "Millisecond-level" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },

  // ============================================================
  // 七、灵心巧手 — 机械臂
  // ============================================================
  {
    id: "linker-arm-a7",
    name: "Linker Arm A7 Robotic Arm",
    category: "robot-arm",
    brand: "LinkerBot",
    price: 4499,
    currency: "USD",
    priceNote: "Ex-Works",
    badge: "Lightweight Collaborative Robotic Arm",
    badgeType: "badge-new",
    tagline: "7 DOF · 600 mm Maximum Working Radius · 3 kg Payload · 5.9 kg Weight · 360 RPM",
    description: "Commercial robotic arm for embodied intelligence and lightweight applications. 7 DOF architecture with large joint rotation ranges for flexible posture adjustment and complex trajectory planning. All-in-one joint design integrating motor, driver, and planetary reducer. Max joint speed 360 RPM. CAN/RS485 communication.",
    images: ["image/Linker Arm A7 Robotic Arm.png", "image/Linker Arm A7 Robotic Arm 1.png", "image/Linker Arm A7 Robotic Arm 2.png", "image/Linker Arm A7 Robotic Arm 3.png"],
    specs: [
      { label: "Degrees of Freedom", value: "7" },
      { label: "Weight", value: "5.9 kg" },
      { label: "Working Radius", value: "600 mm" },
      { label: "Rated Payload", value: "3 kg" },
      { label: "Operating Voltage", value: "48 V" },
      { label: "Communication Interface", value: "CAN / RS485" },
      { label: "Max Power", value: "500 W" },
      { label: "Max Joint Speed", value: "360 RPM" },
      { label: "Operating Temperature", value: "-20°C to 50°C" },
      { label: "Joint Design", value: "All-in-one (motor + driver + planetary reducer)" },
    ],
    github: "https://github.com/linker-bot/linkerhand-ros-sdk",
    contact: { email: "Support@wwntAI.com", phone: "+1-662-681-4342", whatsapp: "+86-189-2582-6701" },
    inStock: true,
    featured: false,
  },
];

// ========== 工具函数 ==========
function getFeaturedProducts(max) {
  return PRODUCTS.filter((p) => p.featured).slice(0, max || 3);
}

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

function formatPrice(price, currency, priceNote) {
  if (!price || price <= 0) return "Price Available Upon Request";
  var formatted = "$" + price.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  if (priceNote) {
    formatted += " " + priceNote;
  }
  return formatted;
}
